name: CI

on:
  push:
  workflow_dispatch:
  pull_request_target:
    types: [labeled]
  
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request_target' || contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ./Library
          key: Library
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Unity Test Results
